// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeDex.Data;

#nullable disable

namespace PokeDex.Data.Migrations
{
    [DbContext(typeof(PokedexDbContext))]
    partial class PokedexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokeDex.Core.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("int");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTypeId");

                    b.HasIndex("SecondaryTypeId");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokeDex.Core.Models.PokemonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Grass"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ice"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Poison"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ground"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Flying"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Psychic"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bug"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ghost"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Dark"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Steel"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("PokeDex.Core.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PokeDex.Core.Models.TeamPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPokemon");
                });

            modelBuilder.Entity("PokeDex.Core.Models.Pokemon", b =>
                {
                    b.HasOne("PokeDex.Core.Models.PokemonType", "PrimaryType")
                        .WithMany()
                        .HasForeignKey("PrimaryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeDex.Core.Models.PokemonType", "SecondaryType")
                        .WithMany()
                        .HasForeignKey("SecondaryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryType");

                    b.Navigation("SecondaryType");
                });

            modelBuilder.Entity("PokeDex.Core.Models.TeamPokemon", b =>
                {
                    b.HasOne("PokeDex.Core.Models.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeDex.Core.Models.Team", "Team")
                        .WithMany("TeamPokemon")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PokeDex.Core.Models.Team", b =>
                {
                    b.Navigation("TeamPokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
